import type { Metadata } from "next";
import { Jost, Geist_Mono } from "next/font/google";
import "./globals.css";

const jost = Jost({
  variable: "--font-jost",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Emergere Technologies",
  description: "Generated by Emergere Technologies",
  icons: {
    icon: [
      { url: "/Emergere-Logo.png", sizes: "32x32", type: "image/png" },
      { url: "/Emergere-Logo.png", sizes: "16x16", type: "image/png" },
    ],
    apple: [{ url: "/Emergere-Logo.png", sizes: "180x180", type: "image/png" }],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning
        className={`${jost.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}